# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Element-Extended
version:      1.17
version_from: lib/HTML/ElementTable.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    HTML::Element:                 3.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
